### ISSUE TITLE
请问和zsummer有神马区别？

### ISSUE THREAD

**Issue by ckcfcc** [zsummer/zsummerX#2]
请问和zsummer有神马区别？

**Comment by zsummer** [comment]
zsummerX用了C++11的特性, 设计上没有变化, 接口上用shared_ptr来做内存管理,  std::bind / std::function来替换zsummer中的回调指针.
整个库的使用变得像脚本语言一样简洁清爽,  而且性能上比zsummer还略有提高.

在这个基础上又编写了一套frame框架,  配合proto4z(工具生成C++ lua C# SQL协议的数据结构, 并且支持HTTP协议), 已经可以直接当作web server, web client去使用, 也可以直接几行代码编译一个生产环境用的服务器(用词可能稍微夸张点).  

现在基本上都是在维护zsummerX,  功能也更为丰富. 

另外用zsummerX为网络模块的开源breeze服务器引擎也逐渐稳定下来. 再稍微投入点时间打磨一下 就可以作为成熟的服务器引擎来使用了.
