### ISSUE TITLE
客户端发送请求的时候遇到的问题

### ISSUE THREAD

**Issue by tigerpro** [zsummer/zsummerX#9]
if (_onSendHandler)
    {
        LCF("TcpSocket already send." << logSection());
        return false;
    }
客户端发送一条消息后，后面的消息，一直进这段代码，是没有收到发送完成消息，这个状态可以移除么。
我的测试环境是win7 ，服务器和客户端都在同一台笔记本上运行。

**Comment by tigerpro** [comment]
调用WSASend后，再设置sending=true状态，结果异步HANDLE_SEND消息先到达，sending=false，导致这个问题，sending=true放在调用WSASend之前没有问题。

**Comment by zsummer** [comment]
在_onSendHandler回调被调用之前 不允许再次调用该接口. 在回调中和回调后 可以调用该方法.   这个状态不可以移除并且是不允许这样做.    
否则 如果在回调前重复调用便意味着_onSendHandler被覆盖, 上一次的send成功就会回调下一次send赋予的方法, 逻辑是不正确的.
